/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package novice;

import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author ACER
 */
public class GUI extends javax.swing.JFrame {
        Novice player1 = new Novice(50);
        ArrayList<Novice> monster = new ArrayList<Novice>();
    /**
     * Creates new form GUI
     */
    public GUI() {
        monster.add(new Alligator(75));
        monster.add(new Butterfly (50));
        monster.add(new Goblin(50));
        initComponents();
        
    }
public static String printNovice(Novice p1){
       // Novice player1 = new Novice(100);
        String hp = "Novice "+"\nAttack: " + p1.getatk()+"\nKill: " +p1.getexp() + "\nHp: " + p1.gethp()+"\nLevel:" + p1.getlevel()+"\nGuard:"+ p1.getguard();//+
               // Novice.atk+"\nHealth: ";
                
        return hp;
    }
 public static String printMonster(ArrayList<Novice> monster,int member){
        String hp = "Attack: "+
                monster.get(member).getatk()+"\nHp: " + monster.get(member).gethp(); 
               
        
        return hp;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 149, 212));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 202, 212));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Novice");
        jButton3.setActionCommand("Novice");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, 29));

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1.setFont(new java.awt.Font("Yu Gothic Light", 0, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Magician", "Swordsman", "Archer" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 80, 32));

        jTextArea1.setBackground(new java.awt.Color(255, 102, 102));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, 142));

        jComboBox3.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alligator", "Goblin", "Butterfly" }));
        jComboBox3.setToolTipText("");
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 86, 49));

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(255, 0, 51));
        jTextPane1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jTextPane1.setText("Status");
        jScrollPane2.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 90, 40));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Novice");
        jButton2.setActionCommand("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 92, 49));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 205, 136));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 224, 189));

        jComboBox4.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox4.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Orange", "Apple", "Grape" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 186, 147));

        jTextArea2.setBackground(new java.awt.Color(153, 51, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 186, 110));

        jTextArea3.setBackground(new java.awt.Color(153, 0, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 205, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Attack");
        jButton1.setActionCommand("Atte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Attack");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/novice/pic/พื้นหลัง.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 750, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        switch(jComboBox1.getSelectedItem().toString()){
			case "Magician":
				jLabel2.setIcon(new ImageIcon(getClass().getResource("pic/2.png")));
                                player1.addatk(100);
                                jTextArea1.setText(printNovice(player1));
                               
				break;
			case "Swordsman":
				jLabel2.setIcon(new ImageIcon(getClass().getResource("pic/9.png")));
                                 player1.addatk(70);
                                 jTextArea1.setText(printNovice(player1));

				break;
			case "Archer":
				jLabel2.setIcon(new ImageIcon(getClass().getResource("pic/1.png")));
                                player1.addatk(80);
                                jTextArea1.setText(printNovice(player1));

				break;
			
                                
		}
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(getClass().getResource("pic/10.png")));
         jTextArea1.setText(printNovice(player1));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        switch(jComboBox3.getSelectedItem().toString()){
			case "Goblin":
				jLabel3.setIcon(new ImageIcon(getClass().getResource("pic/25.gif")));
                                //jTextArea1.setText(printPokemons(pokemons,0));
                                 monster.get(2).addatk(70);
                                jTextArea3.setText(printMonster(monster,2));

				break;
			case "Butterfly":
				jLabel3.setIcon(new ImageIcon(getClass().getResource("pic/giphy.gif")));
                                //jTextArea1.setText(printPokemons(pokemons,1));
                                  monster.get(1).addatk(50);
                                jTextArea3.setText(printMonster(monster,1));
                                
				break;
			case "Alligator":
				jLabel3.setIcon(new ImageIcon(getClass().getResource("pic/26.gif")));
                                //jTextArea1.setText(printPokemons(pokemons,2));
                                 monster.get(0).addatk(60);
                                jTextArea3.setText(printMonster(monster,0));

				break;
			
                                
		}
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLabel5.setIcon(new ImageIcon(getClass().getResource("pic/30.png")));
         jTextArea2.setText(printNovice(player1));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
         switch(jComboBox4.getSelectedItem().toString()){
			case "Orange":
				jLabel4.setIcon(new ImageIcon(getClass().getResource("pic/food3.png")));
                                player1.addhp(50);
                                jTextArea1.setText(printNovice(player1));
                                
                                //jTextArea1.setText(printPokemons(pokemons,0));

				break;
			case "Apple":
				jLabel4.setIcon(new ImageIcon(getClass().getResource("pic/food1.png")));
                                //jTextArea1.setText(printPokemons(pokemons,1));
                                 player1.addhp(70);
                                 jTextArea1.setText(printNovice(player1));

				break;
			case "Grape":
				jLabel4.setIcon(new ImageIcon(getClass().getResource("pic/food2.png")));
                                //jTextArea1.setText(printPokemons(pokemons,2));
                                 player1.addhp(100);
                                 jTextArea1.setText(printNovice(player1));

				break;
			
                                
		}
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         switch(jComboBox3.getSelectedItem().toString()){
			case "Alligator":
				
                               monster.get(0).Attacked(player1.getatk());
                                if(monster.get(0).gethp()<=0)
                                     player1.addexp();
                                if(player1.getexp()%5==0)
                                    player1.setlevel();
                                
                                jTextArea2.setText(printNovice(player1));
                                jTextArea3.setText(printMonster(monster,0));
                                
                                

				break;
                        case "Butterfly":
				 monster.get(1).Attacked(player1.getatk());
                                if(monster.get(1).gethp()<=0)
                                     player1.addexp();
                                if(player1.getexp()%5==0)
                                    player1.setlevel();
                                jTextArea2.setText(printNovice(player1));
                                jTextArea3.setText(printMonster(monster,1));
                                

				break;
                       
			case "Goblin":
				 monster.get(2).Attacked(player1.getatk());
                                if(monster.get(2).gethp()<=0)
                                    player1.addexp();
                                if(player1.getexp()%5==0)
                                    player1.setlevel();
                                jTextArea2.setText(printNovice(player1));
                                jTextArea3.setText(printMonster(monster,2));
                                
				break;
                      
		}
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         
                                
      switch(jComboBox3.getSelectedItem().toString()){
			case "Alligator":
				if(player1.getguard()>=0){
                                    player1.Attacked(monster.get(0).getatk()-30);
                                    player1.devguard();
                                }
                                else
                                 
                                 player1.Attacked(monster.get(0).getatk());
                           
                                jTextArea2.setText(printNovice(player1));

				break;
                        case "Butterfly":
                            if(player1.getguard()>=0){
				   player1.Attacked(monster.get(1).getatk()-40);
                                    player1.devguard();
                            }
                            else
                                player1.Attacked(monster.get(1).getatk());
                                jTextArea2.setText(printNovice(player1));

				break;
                       
			case "Goblin":
                            if(player1.getguard()>=0){
				   player1.Attacked(monster.get(2).getatk()-50);
                                    player1.devguard();
                            }
                            else
                                player1.Attacked(monster.get(2).getatk());
                                jTextArea2.setText(printNovice(player1));

				break;
         }
                          
           
                            
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
